### ISSUE TITLE
[feat] 운영 서버 배포 준비

### ISSUE THREAD

**Issue by tkdwns414** [OMZigak/KKUMER#110]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)
운영 서버 배포를 위한 작업들을 진행합니다.
운영 서버가 될 브랜치는 main 브랜치로 이름 짓습니다.

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [x] ci/cd prod 스크립트 작성
- [x] application prod 버전 작성
- [x] github secrets prod 버전 작성
- [x] dockerfile prod 버전 작성 
- [x] discord prod 추가
