### ISSUE TITLE
[fix] CI/CD 트리거 고치기

### ISSUE THREAD

**Issue by tkdwns414** [OMZigak/KKUMER#129]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)
여전히 고쳐지지 않은 CI/CD 타겟을 고칩니다.

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [ ] develop으로 머지되는 PR이 생성됐을 때만 develop-CI가 돌아가게
- [ ] develop에 Push가 됐을 때만 develop-CD가 돌아가게
- [ ] main으로 머지되는 PR이 생성됐을 때만 prod-CI가 돌아가게
- [ ] main으로 push가 됐을 때만 prod-CD가 돌아가게
