### ISSUE TITLE
[fix] 약속 완료 API 수정

### ISSUE THREAD

**Issue by tkdwns414** [OMZigak/KKUMER#41]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)
약속 완료 API에 추가작업 

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [ ] 도착 안한 유저 있으면 에러
- [ ] 약속 마칠 때 참여자의 userInfo 다 업데이트
- [ ] 약속 시간이 실제 시간보다 전이면 완료 불가
