### ISSUE TITLE
[fix] API 응답 관련 개선사항들 적용

### ISSUE THREAD

**Issue by tkdwns414** [OMZigak/KKUMER#49]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)
1. API의 응답 중 'id'같은 경우 'userId', 'memberId' 등 어떤 id인지 더 자세하게 내려주기로 변경
2. ErrorCode 세분화 다시 진행
3. ErrorCode 메시지 리라이팅

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [x] API 명세서에 success 추가
- [ ] dto에 id인 것들 모두 entityId 형태로 수정
- [x] ErrorCode의 도메인별 번호 재정리
- [ ] ErrorCode의 메시지 재작성
- [ ] API 명세서에 에러코드 및 상황 설명 추가
