### ISSUE TITLE
[fix] 추가 개선사항 적용

### ISSUE THREAD

**Issue by tkdwns414** [OMZigak/KKUMER#60]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)
1. 상수 고치기(콘스탄트 클래스명, NaverService 등 한 번만 쓰이는 애들은 클래스 내에 빼기)
2. 리스트.of 말고 emptyList()로 반환
3. 전체 코드블록으로 처리하기 -> +로 하면 따로 메모리가 들어감
4. 조인문 수정 Fetch Join 사용할 수 있는 곳 사용하기
BatchSize 사용하여 In 하기
5. 다이나믹 업데이트, 다이나믹 인서트
6. DTO vs VO
7. IsMember 분리
8. requestMapping 삭제 및 versioning 컨트롤러 단위에서 메소드 단위로 변경

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [x] Constant 클래스 하나로 관리되는 상수 클래스를 세분화 및 static 변수 선언
- [x] List.of() -> List.emptyList()
- [x] Query의 SQL 코드블럭으로 수정(메모리 사용 줄이기)
- [x] Fetch Join 사용
- [x] 릴레이션 BatchSize 사용 
- [x] ~~Dynamic Update, Insert~~ -> 사용하지 않기로 결정
- [x] ~~DTO -> VO~~ -> 다음부터 하기~
- [x] IsMember 분리
- [x] requestMapping 삭제 및 versioning 컨트롤러 단위에서 메소드 단위로 변경
