### ISSUE TITLE
[fix] S3 multipart 이미지 관련 수정

### ISSUE THREAD

**Issue by chaewonni** [OMZigak/KKUMER#91]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)
이미지 용량이 1MB이하만 업로드되는 오류 수정 및 이미지 확장자 추가

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [ ] HEIC 확장자 추가
- [ ] 이미지 용량 수정
- [ ] NGINX 파일 업로드 용량 제한 설정
