### ISSUE TITLE
[feat] 약속 조회 관련 API 수정

### ISSUE THREAD

**Issue by chaewonni** [OMZigak/KKUMER#94]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)
약속 조회 관련 API의 수정 사항 반영

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [x] dday 약속일자에 따라 음수 양수 모두 나타나게 수정
- [x] 시간 형식 통일
- [x] 특정 모임의 약속 목록 API에 isParticipant 쿼리 파라미터 추가 
- [x] 약속 상세 정보 조회 API isParticipant 필드 추가
